POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "name" : "akhil",
  "email" : "akhil@gmail.com",
  "password" : "12345"
}

###

POST http://localhost:5000/api/users/auth
Content-Type: application/json

{
  "email" : "ken940005@gmail.com",
  "password" : "123"
}

###

GET http://localhost:5000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDhhZGEwYzk3YTYyZGFhMzFiMWQ0ZjgiLCJpYXQiOjE2ODY4Mjg4MDd9.S_dWd0KM3VHaCbbpNEeFC5ShTMrdF9GmLCFXEPFj420

###

PUT http://localhost:5000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDhhZGEwYzk3YTYyZGFhMzFiMWQ0ZjgiLCJpYXQiOjE2ODY4MjkyNDJ9.53RPV5SKqTQ6AGxm6JPngWas_Bv4GkmTW66YID5LhI0
Content-Type: application/json

{
  "name" : "Akhil",
  "email" : "akhil@gemail.com",
  "imgSrc" : "nothing12"
}

###

PATCH http://localhost:5000/api/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk5NmI4YTYxN2I1MzVlNzRiZjBhM2MiLCJpYXQiOjE2ODgxMDM2NDV9.4JcfTxrmPHbC41v5AC1jYtdxHrtOX5W2AsamGo9i4bk

###

POST  http://localhost:5000/api/users/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDhkMzJiNjUwZDJjMjM5ZGU5MWM5ZjAiLCJpYXQiOjE2ODY5NzUxODB9.C6914X-vdG75l0Fvxy0ijpLCgyGwIsgee8EDT_EvCzs
Content-Type: application/json

{
  "userId" : "648d32b650d2c239de91c9f0",
  "dateOfPost" : "rw",
  "discription" : "nothing12",
  "content" : "nothign",
  "likes" : 12,
  "Comments" : "nothing"
  
}

###

GET http://localhost:5000/api/users/requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk5NmI4YTYxN2I1MzVlNzRiZjBhM2MiLCJpYXQiOjE2ODgxMDM2NDV9.4JcfTxrmPHbC41v5AC1jYtdxHrtOX5W2AsamGo9i4bk

###

POST http://localhost:5000/api/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk5NmI4YTYxN2I1MzVlNzRiZjBhM2MiLCJpYXQiOjE2ODg3NTA4ODZ9.SIS2MnJefVDkqOXpfEY2CbZ6KPPEWHIphBmQ7lXP0GI
Content-Type: application/json

{
  "userId" : "6498179cfecb3611def07876"
}


###

GET http://localhost:5000/api/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk5NmI4YTYxN2I1MzVlNzRiZjBhM2MiLCJpYXQiOjE2ODg3NTA4ODZ9.SIS2MnJefVDkqOXpfEY2CbZ6KPPEWHIphBmQ7lXP0GI


###

POST http://localhost:5000/api/chat/group
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk5NmI4YTYxN2I1MzVlNzRiZjBhM2MiLCJpYXQiOjE2ODg3NTA4ODZ9.SIS2MnJefVDkqOXpfEY2CbZ6KPPEWHIphBmQ7lXP0GI
Content-Type: application/json

{
  "name" : "test Group",
  "users" : "[\"64996b8a617b535e74bf0a3c\",\"649e81c51ed19f8cff583961\"]"
}



###

PUT http://localhost:5000/api/chat/rename
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk5NmI4YTYxN2I1MzVlNzRiZjBhM2MiLCJpYXQiOjE2ODg3NTA4ODZ9.SIS2MnJefVDkqOXpfEY2CbZ6KPPEWHIphBmQ7lXP0GI
Content-Type: application/json

{
  "chatId" : "64a91da954457fa5b33b20b0",
  "chatName" : "Test update"
}




###

PUT http://localhost:5000/api/chat/add/group
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk5NmI4YTYxN2I1MzVlNzRiZjBhM2MiLCJpYXQiOjE2ODg3NTA4ODZ9.SIS2MnJefVDkqOXpfEY2CbZ6KPPEWHIphBmQ7lXP0GI
Content-Type: application/json

{
  "chatId" : "64a91da954457fa5b33b20b0",
  "userId" : "6498179cfecb3611def07876"
}



###

PUT http://localhost:5000/api/chat/remove/group
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk5NmI4YTYxN2I1MzVlNzRiZjBhM2MiLCJpYXQiOjE2ODg3NTA4ODZ9.SIS2MnJefVDkqOXpfEY2CbZ6KPPEWHIphBmQ7lXP0GI
Content-Type: application/json

{
  "chatId" : "64a91da954457fa5b33b20b0",
  "userId" : "6498179cfecb3611def07876"
}

